version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command:
      - mongod

  mongo_seed:
    build: mongo_seed
    links:
      - mongodb
    depends_on:
      - mongodb

  server:
    build: "../../server"
    environment:
      - NODE_ENV=production
      - MONGO_DATABASE=mongodb://mongodb/malwarebytes
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb